# travis's ruby-head doesn't compatible for some native extension.
before_install:
  - gem install nokogiri ffi yajl-ruby redcarpet -- --with-cflags='--std=gnu99'

bundler_args: --without development

rvm:
  - ree
  - 1.9.2
  - 1.9.3
  - ruby-head

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle exec misc/standalone_cgi/bin/server -d

script: bundle exec rake test spec

env:
  - TEST_MODE=rack
  - TEST_MODE=rdb
  - TEST_MODE=webrick

notifications:
  irc: "irc.freenode.org#tdiary"

matrix:
  allow_failures:
    # webrick mode is unstable results...
    - env: TEST_MODE=webrick
    # travis's ruby-head doesn't supported to selenium-webdriver.
    - rvm: ruby-head
      env: TEST_MODE=webrick
