before_install:
  - gem install nokogiri ffi yajl-ruby -- --with-cflags='--std=gnu99'
  - gem install redcarpet -v 2.2.0 -- --with-cflags='--std=gnu99'

bundler_args: --without development

rvm:
  - ree
  - 1.9.2
  - 1.9.3
  - ruby-head

script: bundle exec rake test spec spec:acceptance:rdb

notifications:
  irc: "irc.freenode.org#tdiary"
